let projectId=localStorage.getItem('behiveProjectId');
let questions=[];
let rootNode=null;
let selectedQuestion=null;
let dialogMode='add';
const findings=[];
let library=[];
let bibliography=[];
let discovery={nodes:[],edges:[],frontiers:[],hypotheses:[],cycles:[],active:false};
let frontierPanel='frontiers';
const graphZoomers={};
let evolution={versions:[],experiments:[],events:[],audits:[]};
let deepAnalysis=null;
let researchGaps=[];
let analysisRevisions=[];
let gapPollTimer=null;
let architectureDraft=null;
let architectProgressTimer=null;
const agents=[['PL','Planner','Ranking research frontier','ACTIVE'],['SC','Scout','Searching sources','ACTIVE'],['VR','Verifier','Checking claims','ACTIVE'],['CN','Connector','Mapping cross-thread links','IDLE']];
const $=selector=>document.querySelector(selector);
const investigationDlg=$('#investigationDialog');
function escapeHtml(value){const div=document.createElement('div');div.textContent=value??'';return div.innerHTML}
async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.detail||data.message||`Request failed (${response.status})`);return data}
async function ensureProject(){
 if(projectId){
  try{await loadTree();return}
  catch(error){localStorage.removeItem('behiveProjectId');projectId=null;rootNode=null;selectedQuestion=null}
 }
 try{
  const created=await api('/projects',{method:'POST',body:JSON.stringify({title:$('#projectTitle').textContent.trim(),root_question:$('#rootQuestion').textContent.trim(),cadence_minutes:1440})});
  projectId=created.id;localStorage.setItem('behiveProjectId',projectId);await loadTree();
 }catch(error){$('#missionMessage').textContent=`Project storage unavailable: ${error.message}`}
}
async function loadTree(){
 const data=await api(`/projects/${projectId}/map`);const nodes=data.nodes||[];
 rootNode=nodes.find(n=>n.type==='question'&&!n.parent_id)||null;
 questions=nodes.filter(n=>n.type==='question'&&n.parent_id&&n.status!=='archived').map(n=>({id:n.id,parentId:n.parent_id,title:n.label,depth:n.depth,confidence:Math.round((n.confidence||0)*100),findings:0,kind:(n.kind||'followup').toUpperCase(),priority:n.priority,status:n.status}));
 findings.splice(0,findings.length,...nodes.filter(n=>n.type==='finding').map(f=>({time:'SAVED FINDING',score:Math.round((f.confidence||0)*100),text:f.label,source:f.source_url||'Source pending'})));
 if(rootNode){$('#rootQuestion').textContent=rootNode.label;$('#rootTreeTitle').textContent=rootNode.label;$('#rootTreeMeta').textContent=`${Math.round((rootNode.confidence||0)*100)}% confidence · priority ${Math.round((rootNode.priority||1)*100)}%`;$('#projectTitle').textContent=rootNode.label.length>42?rootNode.label.slice(0,39)+'…':rootNode.label}
 await loadFrontier();
 render();
}
async function loadFrontier(){try{const data=await api(`/projects/${projectId}/frontier?limit=1`);const item=data.frontier?.[0];$('#frontierTitle').textContent=item?.question||'No frontier ranked yet';$('#frontierMeta').textContent=item?`Discovery score ${Math.round((item.score||0)*100)}%`:'Add questions or start research to rank the next thread.'}catch(error){$('#frontierTitle').textContent='Frontier unavailable';$('#frontierMeta').textContent=error.message}}
function render(){
 $('#questionTree').innerHTML=questions.sort((a,b)=>a.depth-b.depth||b.priority-a.priority).map(q=>`<div class="branch" style="margin-left:${Math.max(0,q.depth-1)*24}px"><span class="node"></span><div class="question-card ${selectedQuestion?.id===q.id?'selected':''}" data-id="${q.id}"><span class="tag">${escapeHtml(q.kind)} · ${escapeHtml(q.status)}</span><h3>${escapeHtml(q.title)}</h3><div class="bar"><i style="width:${q.confidence}%"></i></div><small>${q.confidence}% confidence · priority ${Math.round(q.priority*100)}%</small></div></div>`).join('')||'<p class="sub">Select Add question to create the first branch.</p>';
 $('#findingFeed').innerHTML=findings.map(f=>`<article class="finding"><div class="meta"><span>${escapeHtml(f.time)}</span><span class="confidence">${f.score}% confidence</span></div><p>${escapeHtml(f.text)}</p><a href="${f.source?.startsWith('http')?escapeHtml(f.source):'#'}">${escapeHtml(f.source)} →</a></article>`).join('')||'<p class="sub">No findings yet. Verified findings will appear here as research progresses.</p>';
 const questionCount=questions.length+(rootNode?1:0),findingCount=findings.length,confidence=findingCount?Math.round(findings.reduce((sum,f)=>sum+f.score,0)/findingCount):0,coverage=questionCount?Math.round(questions.filter(q=>q.confidence>0).length/questionCount*100):0;
 $('#metricFindings').textContent=findingCount;$('#metricConfidence').textContent=findingCount?(confidence/100).toFixed(2):'—';$('#metricQuestions').textContent=questionCount;$('#navQuestionCount').textContent=questionCount;$('#navFindingCount').textContent=findingCount;$('#navLibraryCount').textContent=findings.filter(f=>f.source?.startsWith('http')).length;$('#navReviewCount').textContent=findings.length;$('#coverageValue').textContent=`${coverage}%`;$('#coverageBar').style.width=`${coverage}%`;$('#coverageNote').textContent=findingCount?`${questions.filter(q=>q.confidence===0).length} questions need evidence`:'No findings yet';
 $('#agents').innerHTML=agents.map(a=>`<div class="agent"><span class="avatar">${a[0]}</span><div><b>${a[1]}</b><small>${a[2]}</small></div><span>${a[3]}</span></div>`).join('');
 document.querySelectorAll('#questionTree .question-card').forEach(card=>{card.onclick=()=>selectQuestion(card.dataset.id);card.ondblclick=()=>openEdit()});
 $('#editQuestion').disabled=!selectedQuestion;drawGraph();
}
function selectQuestion(id){selectedQuestion=questions.find(q=>q.id===id)||null;$('#rootTreeCard').classList.remove('selected');render();$('#addQuestion').textContent=selectedQuestion?'＋ Add child':'＋ Add question'}
async function selectRoot(){if(!rootNode)await ensureProject();if(!rootNode){$('#missionMessage').textContent='The root question could not be loaded. Check database health and refresh.';return}selectedQuestion={id:rootNode.id,title:rootNode.label,depth:0,confidence:Math.round((rootNode.confidence||0)*100),findings:0,kind:'ROOT',priority:rootNode.priority||1,status:rootNode.status||'open',isRoot:true};$('#rootTreeCard').classList.add('selected');render();$('#rootTreeCard').classList.add('selected');$('#addQuestion').textContent='＋ Add child'}
function drawGraph(){const svg=$('#graphSvg');const shown=questions.slice(0,4);let nodes=[{x:450,y:70,t:'Root question',c:'#215b43'}];shown.forEach((q,i)=>nodes.push({x:150+i*200,y:230,t:q.kind,c:'#6989bd'}));findings.slice(0,shown.length).forEach((f,i)=>nodes.push({x:150+i*200,y:410,t:f.score+'% finding',c:'#d99b35'}));let lines=shown.map((_,i)=>`<line x1="450" y1="70" x2="${150+i*200}" y2="230"/>`).join('')+findings.slice(0,shown.length).map((_,i)=>`<line x1="${150+i*200}" y1="230" x2="${150+i*200}" y2="410"/>`).join('');svg.innerHTML=`<g stroke="#c7d0c8" stroke-width="2">${lines}</g>`+nodes.map(n=>`<g><circle cx="${n.x}" cy="${n.y}" r="18" fill="${n.c}"/><text x="${n.x}" y="${n.y+34}" text-anchor="middle" font-size="11" fill="#34443b">${escapeHtml(n.t)}</text></g>`).join('')}
function makeGraphZoomer(svgId,baseBox){const svg=$('#'+svgId);if(!svg)return null;const host=svg.closest('.graph-zoom-host'),readout=host.querySelector('.graph-zoom-readout'),base={...baseBox},state={...baseBox,drag:null,moved:false};const clamp=()=>{state.w=Math.max(base.w*.16,Math.min(base.w*2,state.w));state.h=state.w*(base.h/base.w);state.x=Math.max(base.x-base.w*.5,Math.min(base.x+base.w*1.5-state.w,state.x));state.y=Math.max(base.y-base.h*.5,Math.min(base.y+base.h*1.5-state.h,state.y))};const apply=()=>{clamp();svg.setAttribute('viewBox',`${state.x} ${state.y} ${state.w} ${state.h}`);readout.textContent=`${Math.round(base.w/state.w*100)}%`};const zoom=(factor,cx=state.x+state.w/2,cy=state.y+state.h/2)=>{const oldW=state.w,oldH=state.h;state.w*=factor;state.h*=factor;state.x=cx-(cx-state.x)*(state.w/oldW);state.y=cy-(cy-state.y)*(state.h/oldH);apply()};host.querySelector('.graph-tools').onclick=event=>{const action=event.target.closest('[data-graph-action]')?.dataset.graphAction;if(!action)return;if(action==='zoom-in')zoom(.75);else if(action==='zoom-out')zoom(1.333);else if(action==='fit'){Object.assign(state,base);apply()}else if(action==='expand'){const expanded=host.classList.toggle('graph-expanded');document.body.classList.toggle('graph-expanded-open',expanded);event.target.textContent=expanded?'Close':'Expand';setTimeout(apply,0)}};svg.addEventListener('wheel',event=>{event.preventDefault();const rect=svg.getBoundingClientRect(),cx=state.x+(event.clientX-rect.left)/rect.width*state.w,cy=state.y+(event.clientY-rect.top)/rect.height*state.h;zoom(event.deltaY<0?.82:1.22,cx,cy)},{passive:false});svg.addEventListener('pointerdown',event=>{if(event.button!==0||event.target.closest('[data-node-id],[data-edge-id]'))return;state.drag={x:event.clientX,y:event.clientY,startX:state.x,startY:state.y};state.moved=false;host.classList.add('is-panning');svg.setPointerCapture(event.pointerId)});svg.addEventListener('pointermove',event=>{if(!state.drag)return;const rect=svg.getBoundingClientRect(),dx=event.clientX-state.drag.x,dy=event.clientY-state.drag.y;if(Math.abs(dx)+Math.abs(dy)>3)state.moved=true;state.x=state.drag.startX-dx/rect.width*state.w;state.y=state.drag.startY-dy/rect.height*state.h;apply()});const end=event=>{if(!state.drag)return;state.drag=null;host.classList.remove('is-panning');try{svg.releasePointerCapture(event.pointerId)}catch(_){}};svg.addEventListener('pointerup',end);svg.addEventListener('pointercancel',end);svg.addEventListener('click',event=>{if(state.moved){event.preventDefault();event.stopImmediatePropagation();state.moved=false}},true);apply();return{zoom,fit:()=>{Object.assign(state,base);apply()},state,host}}
graphZoomers.evidence=makeGraphZoomer('graphSvg',{x:0,y:0,w:900,h:520});graphZoomers.discovery=makeGraphZoomer('discoverySvg',{x:0,y:0,w:1000,h:650});document.addEventListener('keydown',event=>{if(event.key!=='Escape')return;Object.values(graphZoomers).forEach(control=>{if(control?.host.classList.contains('graph-expanded')){control.host.classList.remove('graph-expanded');control.host.querySelector('[data-graph-action="expand"]').textContent='Expand'}});document.body.classList.remove('graph-expanded-open')});
async function loadDiscovery(){if(!activeMission)return;try{discovery=await api(`/research/${activeMission}/discovery`);renderDiscovery()}catch(error){$('#discoverySummary').textContent=`Discovery map unavailable: ${error.message}`} }
function scoreChips(scores={}){return ['novelty','testability','impact'].map(k=>`<span>${k} ${Math.round((Number(scores[k])||0)*100)}%</span>`).join('')}
function renderFrontierRail(){const rail=$('#frontierRail');if(frontierPanel==='hypotheses'){rail.innerHTML=(discovery.hypotheses||[]).map(h=>`<article class="hypothesis-card"><div class="frontier-meta"><span>${escapeHtml(h.type)}</span><b>${Math.round((Number(h.scores?.priority)||0)*100)} priority</b></div><h3>${escapeHtml(h.name)}</h3><p>${escapeHtml(h.statement)}</p><div class="score-row">${scoreChips(h.scores)}</div><details><summary>Predictions and discriminators</summary><b>Observable predictions</b><ul>${(h.predictions||[]).map(x=>`<li>${escapeHtml(typeof x==='string'?x:JSON.stringify(x))}</li>`).join('')}</ul><b>Discriminating tests</b><ul>${(h.discriminators||[]).map(x=>`<li>${escapeHtml(typeof x==='string'?x:JSON.stringify(x))}</li>`).join('')}</ul><b>Missing links</b><ul>${(h.missing_links||[]).map(x=>`<li>${escapeHtml(typeof x==='string'?x:JSON.stringify(x))}</li>`).join('')}</ul></details></article>`).join('')||'<div class="empty-frontier">No hypothesis portfolio yet.</div>'}else{rail.innerHTML=(discovery.frontiers||[]).map(f=>`<article class="frontier-card"><div class="frontier-meta"><span>${escapeHtml(f.type)} · ${escapeHtml(f.absence_type)}</span><b>${Math.round((Number(f.priority)||0)*100)}</b></div><h3>${escapeHtml(f.title)}</h3><p>${escapeHtml(f.rationale)}</p><div class="score-row">${scoreChips(f.scores)}</div></article>`).join('')||'<div class="empty-frontier">Run a discovery cycle to locate meaningful unknowns.</div>'}}
function renderDiscovery(){const nodes=(discovery.nodes||[]).slice(0,70),edges=(discovery.edges||[]).filter(e=>nodes.some(n=>n.id===e.source)&&nodes.some(n=>n.id===e.target)).slice(0,120),svg=$('#discoverySvg');const positions={};nodes.forEach((n,i)=>{const ring=i<12?150:i<35?245:315,angle=(i*2.399963229728653)+(i%4)*.13;positions[n.id]={x:500+Math.cos(angle)*ring,y:325+Math.sin(angle)*ring}});const edgeMarkup=edges.map(e=>{const a=positions[e.source],b=positions[e.target];if(!a||!b)return'';return `<g data-edge-id="${escapeHtml(e.id)}"><line class="graph-edge ${escapeHtml(e.state)}" x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"/><line class="graph-edge-hit" x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"><title>Open ${escapeHtml(e.relation)} evidence</title></line></g>`}).join('');const colors={compound:'#7b68a7',receptor:'#537eaa',pathway:'#467a62',cell_type:'#6c9472',disease:'#b45b4c',phenotype:'#bd8637',observation:'#d99b35',process:'#4f826f',measurement:'#798a97',condition:'#9a8664'};const nodeMarkup=nodes.map(n=>{const p=positions[n.id],label=n.label.length>28?n.label.slice(0,26)+'…':n.label;return `<g class="discovery-node" data-node-id="${escapeHtml(n.id)}"><circle cx="${p.x}" cy="${p.y}" r="${n.state==='observed'?12:9}" fill="${colors[n.type]||'#6989bd'}"><title>Open ${escapeHtml(n.label)}</title></circle><text x="${p.x}" y="${p.y+23}" text-anchor="middle">${escapeHtml(label)}</text></g>`}).join('');svg.innerHTML=`<circle cx="500" cy="325" r="82" fill="#e5eddf" stroke="#215b43"/><text x="500" y="320" text-anchor="middle" font-size="13" font-weight="700">EXPLORATORY PROBE</text><text x="500" y="342" text-anchor="middle" font-size="10">click any point or connection</text>${edgeMarkup}${nodeMarkup}`;const cycle=discovery.cycles?.[0];$('#discoverySummary').textContent=`${nodes.length} mapped concepts · ${edges.length} evidence relationships · ${discovery.frontiers?.length||0} open frontiers · ${discovery.hypotheses?.length||0} competing hypotheses${cycle?` · cycle ${cycle.number} ${cycle.status}`:''}`;$('#metricFindings').textContent=nodes.length;$('#metricConfidence').textContent=discovery.frontiers?.length||0;renderFrontierRail()}
async function showDiscovery(){if(!activeMission){missionMessage.textContent='Start or reopen a probe before mapping its frontier.';return}$('.shell').classList.add('discovery-mode');$('#workspace').classList.add('hidden');$('#graphView').classList.add('hidden');$('#collectionView').classList.add('hidden');$('#discoveryView').classList.remove('hidden');await loadDiscovery()}
document.querySelectorAll('[data-frontier-panel]').forEach(button=>button.onclick=()=>{frontierPanel=button.dataset.frontierPanel;document.querySelectorAll('[data-frontier-panel]').forEach(b=>b.classList.toggle('active',b===button));renderFrontierRail()});
$('#runDiscovery').onclick=async()=>{if(!activeMission)return;const button=$('#runDiscovery');button.disabled=true;button.textContent='Mapping frontier…';try{await api(`/research/${activeMission}/discovery/cycles`,{method:'POST'});for(let i=0;i<45;i++){await new Promise(r=>setTimeout(r,3000));await loadDiscovery();if(!discovery.active)break}}catch(error){missionMessage.textContent=`Discovery cycle failed: ${error.message}`}finally{button.disabled=false;button.textContent='Run discovery cycle'}};

async function loadEvolution(){if(!activeMission)return;try{evolution=await api(`/research/${activeMission}/evolution`);renderLabRail()}catch(error){$('#discoverySummary').textContent=`Evolution unavailable: ${error.message}`}}
function listItems(items){return `<ul>${(items||[]).map(x=>`<li>${escapeHtml(typeof x==='string'?x:JSON.stringify(x))}</li>`).join('')}</ul>`}
function renderLabRail(){if(['frontiers','hypotheses'].includes(frontierPanel)){renderFrontierRail();return}const rail=$('#frontierRail');if(frontierPanel==='evolution'){rail.innerHTML=(evolution.versions||[]).map(v=>`<article class="hypothesis-card ${v.survivor?'survivor':'dominated'}"><div class="frontier-meta"><span>G${v.generation} · ${escapeHtml(v.operator)}</span><b>${v.survivor?'PARETO SURVIVOR':'DOMINATED'}</b></div><h3>${escapeHtml(v.name)}</h3><p>${escapeHtml(v.statement)}</p><div class="plausibility"><i style="width:${Math.round((Number(v.posterior)||0)*100)}%"></i></div><small>Plausibility ${Math.round((Number(v.prior)||0)*100)}% → ${Math.round((Number(v.posterior)||0)*100)}% · utility ${Math.round((Number(v.scores?.utility)||0)*100)}%</small><details><summary>Graph, predictions, and assumptions</summary><b>Predictions</b>${listItems(v.predictions)}<b>Discriminators</b>${listItems(v.discriminators)}<b>Assumptions</b>${listItems(v.assumptions)}<b>Safety</b>${listItems(v.safety_risks)}</details></article>`).join('')||'<div class="empty-frontier">No evolved generations yet.</div>'}else if(frontierPanel==='experiments'){rail.innerHTML=(evolution.experiments||[]).map(x=>`<article class="frontier-card experiment-card"><div class="frontier-meta"><span>${escapeHtml(x.type)} · ${escapeHtml(x.status)}</span><b>UTILITY ${Math.round((Number(x.utility)||0)*100)}</b></div><h3>${escapeHtml(x.title)}</h3><p>${escapeHtml(x.description)}</p><div class="score-row"><span>info ${Math.round((Number(x.information_gain)||0)*100)}%</span><span>feasible ${Math.round((Number(x.feasibility)||0)*100)}%</span><span>cost ${Math.round((Number(x.cost)||0)*100)}%</span></div><details><summary>Outcomes and required data</summary><b>Possible outcomes</b>${listItems(x.outcomes)}<b>Required data</b>${listItems(x.required_data)}</details></article>`).join('')||'<div class="empty-frontier">No discriminating tests ranked yet.</div>'}else if(frontierPanel==='timeline'){rail.innerHTML=(evolution.events||[]).map(x=>`<article class="frontier-card timeline-card"><div class="frontier-meta"><span>${escapeHtml(x.type)}</span><b>${escapeHtml(String(x.created_at||''))}</b></div><h3>${escapeHtml(x.subject_type)} ${escapeHtml(x.subject_id||'population')}</h3><p>${escapeHtml(x.reason||'Graph state changed')}</p></article>`).join('')||'<div class="empty-frontier">No evolution events yet.</div>'}else{rail.innerHTML=(evolution.audits||[]).map(x=>`<article class="frontier-card audit-card"><div class="frontier-meta"><span>${escapeHtml(x.severity)} · ${escapeHtml(x.type)}</span><b>${escapeHtml(x.status)}</b></div><h3>${escapeHtml(x.message)}</h3><p>${escapeHtml(x.remediation||'')}</p></article>`).join('')||'<div class="empty-frontier">Graph audit found no open quality problems.</div>'}}
async function showDiscoveryLab(){if(!activeMission){missionMessage.textContent='Start or reopen a probe before opening the Discovery Laboratory.';return}$('.shell').classList.add('discovery-mode');$('#workspace').classList.add('hidden');$('#graphView').classList.add('hidden');$('#collectionView').classList.add('hidden');$('#discoveryView').classList.remove('hidden');await Promise.all([loadDiscovery(),loadEvolution()])}
async function evolvePopulation(){if(!activeMission)return;const button=$('#evolveHypotheses');button.disabled=true;button.textContent='Evolving…';try{const result=await api(`/research/${activeMission}/evolution/generations`,{method:'POST'});missionMessage.textContent=`Generation ${result.generation}: ${result.versions} variants, ${result.survivors} Pareto survivors, ${result.experiments} tests`;frontierPanel='evolution';document.querySelectorAll('[data-frontier-panel]').forEach(b=>b.classList.toggle('active',b.dataset.frontierPanel==='evolution'));await loadEvolution()}catch(error){missionMessage.textContent=`Evolution failed: ${error.message}`}finally{button.disabled=false;button.textContent='Evolve hypotheses'}}
$('#evolveHypotheses').onclick=evolvePopulation;

function contextHtml(value){const entries=Object.entries(value||{});return entries.length?`<div class="context-grid">${entries.map(([k,v])=>`<b>${escapeHtml(k)}</b><span>${escapeHtml(Array.isArray(v)?v.join(', '):typeof v==='object'?JSON.stringify(v):v)}</span>`).join('')}</div>`:'<p>No experimental context was recorded.</p>'}
function inspectorShell(title,state,body){$('#frontierRail').innerHTML=`<div class="map-inspector"><div class="inspector-head"><button class="inspector-back" data-inspector-back>← Back to ${escapeHtml(frontierPanel)}</button><div class="inspector-state">${escapeHtml(state||'')}</div><h3>${escapeHtml(title)}</h3></div>${body}</div>`}
function connectionButton(edge,node){return `<button class="connection-row" data-inspect-edge="${escapeHtml(edge.id)}"><span>${escapeHtml(node?.label||'Unknown')} · ${escapeHtml(edge.relation)}</span><b>${escapeHtml(edge.state)}</b></button>`}
function inspectNode(nodeId){const node=discovery.nodes.find(n=>n.id===nodeId);if(!node)return;const connected=discovery.edges.filter(e=>e.source===nodeId||e.target===nodeId),sources=[...new Set(connected.map(e=>e.evidence_url).filter(Boolean))],frontiers=discovery.frontiers.filter(f=>f.source===nodeId||f.target===nodeId),hypotheses=discovery.hypotheses.filter(h=>(h.path_nodes||[]).some(x=>x===nodeId||String(x).toLowerCase()===node.label.toLowerCase()));inspectorShell(node.label,`${node.type} · ${node.state}`,`<section class="inspector-section"><h4>Meaning in this map</h4><p>${escapeHtml(node.description||'No description was extracted.')}</p></section><section class="inspector-section"><h4>Recorded context</h4>${contextHtml(node.context)}</section><section class="inspector-section"><h4>Connected evidence (${connected.length})</h4>${connected.map(e=>connectionButton(e,discovery.nodes.find(n=>n.id===(e.source===nodeId?e.target:e.source)))).join('')||'<p>No explicit edges.</p>'}</section><section class="inspector-section"><h4>Underlying sources (${sources.length})</h4>${sources.map(url=>`<a class="inspector-link" href="${escapeHtml(url)}" target="_blank" rel="noopener">Open gathered evidence ↗<br>${escapeHtml(url)}</a>`).join('')||'<p>No direct source attached; treat this point as an organizing concept.</p>'}</section><section class="inspector-section"><h4>Open frontiers and ideas</h4>${frontiers.map(f=>`<button class="connection-row" data-inspect-frontier="${escapeHtml(f.id)}"><span>${escapeHtml(f.title)}</span><b>${escapeHtml(f.absence_type)}</b></button>`).join('')}${hypotheses.map(h=>`<button class="connection-row" data-inspect-seed="${escapeHtml(h.id)}"><span>${escapeHtml(h.name)}</span><b>hypothesis</b></button>`).join('')||(!frontiers.length?'<p>No hypothesis path currently references this point.</p>':'')}</section>`) }
function inspectEdge(edgeId){const edge=discovery.edges.find(e=>e.id===edgeId);if(!edge)return;const source=discovery.nodes.find(n=>n.id===edge.source),target=discovery.nodes.find(n=>n.id===edge.target);inspectorShell(`${source?.label||'Unknown'} → ${target?.label||'Unknown'}`,`${edge.relation} · ${edge.state} · ${Math.round((Number(edge.confidence)||0)*100)}%`,`<section class="inspector-section"><h4>Relationship</h4><button class="connection-row" data-inspect-node="${escapeHtml(edge.source)}"><span>${escapeHtml(source?.label||edge.source)}</span><b>source point</b></button><button class="connection-row" data-inspect-node="${escapeHtml(edge.target)}"><span>${escapeHtml(target?.label||edge.target)}</span><b>target point</b></button></section><section class="inspector-section"><h4>Underlying evidence</h4><div class="evidence-quote">${escapeHtml(edge.excerpt||'No supporting excerpt was stored.')}</div>${edge.evidence_url?`<a class="inspector-link" href="${escapeHtml(edge.evidence_url)}" target="_blank" rel="noopener">Open original gathered source ↗<br>${escapeHtml(edge.evidence_url)}</a>`:'<p>No source URL: this relationship must not be treated as observed evidence.</p>'}</section><section class="inspector-section"><h4>Conditions and boundaries</h4>${contextHtml(edge.conditions)}</section><section class="inspector-section inspector-actions"><button data-counterfactual="${escapeHtml(edge.id)}">What if this connection is false?</button></section>`)}
function inspectFrontier(id){const f=discovery.frontiers.find(x=>x.id===id);if(!f)return;inspectorShell(f.title,`${f.type} · ${f.absence_type} · priority ${Math.round((Number(f.priority)||0)*100)}%`,`<section class="inspector-section"><h4>Why this is a frontier</h4><p>${escapeHtml(f.rationale)}</p></section><section class="inspector-section"><h4>Search and validation strategy</h4>${contextHtml(f.search_strategy)}</section><section class="inspector-section"><h4>Frontier scores</h4>${contextHtml(f.scores)}</section>${f.source?`<button class="connection-row" data-inspect-node="${escapeHtml(f.source)}"><span>Open source-side concept</span><b>map point</b></button>`:''}${f.target?`<button class="connection-row" data-inspect-node="${escapeHtml(f.target)}"><span>Open target-side concept</span><b>map point</b></button>`:''}`)}
function inspectSeed(id){const h=discovery.hypotheses.find(x=>x.id===id);if(!h)return;inspectorShell(h.name,`${h.type} · ${h.status}`,`<section class="inspector-section"><h4>Proposed idea — not a finding</h4><p>${escapeHtml(h.statement)}</p><p>${escapeHtml(h.reasoning)}</p></section><section class="inspector-section"><h4>Missing links</h4>${listItems(h.missing_links)}</section><section class="inspector-section"><h4>Observable predictions</h4>${listItems(h.predictions)}</section><section class="inspector-section"><h4>Discriminating tests</h4>${listItems(h.discriminators)}</section><section class="inspector-section"><h4>Assumptions and safety</h4>${listItems(h.assumptions)}${listItems(h.safety_risks)}</section>`)}
function inspectVersion(id){const v=evolution.versions.find(x=>x.id===id);if(!v)return;inspectorShell(v.name,`generation ${v.generation} · ${v.operator} · ${v.survivor?'Pareto survivor':'dominated'}`,`<section class="inspector-section"><h4>Evolved possibility</h4><p>${escapeHtml(v.statement)}</p><p>${escapeHtml(v.rationale)}</p><div class="plausibility"><i style="width:${Math.round((Number(v.posterior)||0)*100)}%"></i></div><p>Transparent plausibility update: ${Math.round((Number(v.prior)||0)*100)}% → ${Math.round((Number(v.posterior)||0)*100)}%</p></section><section class="inspector-section"><h4>Hypothesis subgraph</h4>${contextHtml(v.graph)}</section><section class="inspector-section"><h4>Predictions</h4>${listItems(v.predictions)}</section><section class="inspector-section"><h4>Discriminators</h4>${listItems(v.discriminators)}</section><section class="inspector-section"><h4>Assumptions</h4>${listItems(v.assumptions)}</section><section class="inspector-section"><h4>Safety risks</h4>${listItems(v.safety_risks)}</section><section class="inspector-section"><h4>Competition scores</h4>${contextHtml(v.scores)}</section>`)}
function inspectExperiment(id){const x=evolution.experiments.find(v=>v.id===id);if(!x)return;inspectorShell(x.title,`${x.type} · ${x.status} · utility ${Math.round((Number(x.utility)||0)*100)}%`,`<section class="inspector-section"><h4>Test design</h4><p>${escapeHtml(x.description)}</p></section><section class="inspector-section"><h4>Hypotheses distinguished</h4>${listItems(x.hypotheses)}</section><section class="inspector-section"><h4>Possible outcomes</h4>${listItems(x.outcomes)}</section><section class="inspector-section"><h4>Required data</h4>${listItems(x.required_data)}</section><section class="inspector-section"><h4>Decision metrics</h4>${contextHtml({information_gain:x.information_gain,feasibility:x.feasibility,cost:x.cost,duration:x.duration,safety_risk:x.safety_risk,utility:x.utility})}</section>`)}
$('#discoverySvg').onclick=event=>{const node=event.target.closest('[data-node-id]'),edge=event.target.closest('[data-edge-id]');if(node)inspectNode(node.dataset.nodeId);else if(edge)inspectEdge(edge.dataset.edgeId)};
$('#frontierRail').onclick=async event=>{if(event.target.closest('[data-inspector-back]')){renderLabRail();return}const node=event.target.closest('[data-inspect-node]'),edge=event.target.closest('[data-inspect-edge]'),frontier=event.target.closest('[data-inspect-frontier]'),seed=event.target.closest('[data-inspect-seed]'),counter=event.target.closest('[data-counterfactual]');if(node){inspectNode(node.dataset.inspectNode);return}if(edge){inspectEdge(edge.dataset.inspectEdge);return}if(frontier){inspectFrontier(frontier.dataset.inspectFrontier);return}if(seed){inspectSeed(seed.dataset.inspectSeed);return}if(counter){counter.disabled=true;counter.textContent='Tracing dependencies…';const result=await api(`/research/${activeMission}/counterfactual/${counter.dataset.counterfactual}`);counter.closest('.inspector-section').insertAdjacentHTML('beforeend',`<p><b>${result.collapse_count}</b> surviving hypotheses depend on this connection; <b>${result.remaining_survivors}</b> remain if it is false.</p><p>${escapeHtml(result.recommended_action)}</p>`);counter.remove();return}const card=event.target.closest('article');if(!card)return;const cards=[...$('#frontierRail').querySelectorAll('article')],index=cards.indexOf(card);if(frontierPanel==='frontiers')inspectFrontier(discovery.frontiers[index]?.id);else if(frontierPanel==='hypotheses')inspectSeed(discovery.hypotheses[index]?.id);else if(frontierPanel==='evolution')inspectVersion(evolution.versions[index]?.id);else if(frontierPanel==='experiments')inspectExperiment(evolution.experiments[index]?.id)};

const dlg=$('#questionDialog');
const architectDlg=$('#architectDialog');
function architectSeed(){return [rootNode?.label||$('#rootQuestion').textContent.trim(),...questions.map(q=>`${'  '.repeat(Math.max(0,q.depth-1))}- ${q.title}`)].filter(Boolean).join('\n')}
function resetArchitectStatus(){if(architectProgressTimer){clearInterval(architectProgressTimer);architectProgressTimer=null}$('#architectEmpty').classList.remove('working');$('#architectLoader').hidden=true;$('#architectSpark').textContent='✦';$('#architectStatus').textContent='Your reframed tree will appear here';$('#architectStatusDetail').textContent='Nothing changes until you choose Replace tree or Merge branches.'}
$('#openArchitect').onclick=()=>{if(investigationDlg.open)investigationDlg.close();$('#architectDump').value=architectSeed();architectureDraft=null;$('#architectEmpty').hidden=false;$('#architectResult').hidden=true;resetArchitectStatus();if(!architectDlg.open)architectDlg.showModal()};
$('#closeArchitect').onclick=()=>{resetArchitectStatus();architectDlg.close()};
function renderArchitectureDraft(){const a=architectureDraft?.architecture;if(!a)return;$('#architectEmpty').hidden=true;$('#architectResult').hidden=false;$('#architectRoot').textContent=a.root_question;$('#architectScope').textContent=a.scope||'No additional scope boundaries supplied.';$('#architectNotes').innerHTML=(a.reframing_notes||[]).map(note=>`<p>↳ ${escapeHtml(note)}</p>`).join('')+(a.assumptions||[]).map(note=>`<p class="assumption">Assumption: ${escapeHtml(note)}</p>`).join('');$('#architectTree').innerHTML=(a.questions||[]).map(q=>`<article style="margin-left:${Math.max(0,q.depth-1)*24}px"><div><span>${escapeHtml(q.kind)} · P${Math.round(q.priority*100)}</span><b>${escapeHtml(q.question)}</b><small>${escapeHtml(q.rationale)}</small><em>Evidence: ${escapeHtml(q.evidence_target)}</em></div></article>`).join('')}
$('#generateArchitecture').onclick=async()=>{const button=$('#generateArchitecture'),brain_dump=$('#architectDump').value.trim();if(brain_dump.length<15){$('#architectStatus').textContent='Add more detail first';$('#architectStatusDetail').textContent='Give the architect at least one complete sentence.';return}button.disabled=true;button.textContent='Architecting…';architectureDraft=null;$('#architectResult').hidden=true;$('#architectEmpty').hidden=false;$('#architectEmpty').classList.add('working');$('#architectLoader').hidden=false;$('#architectSpark').textContent='✦';const started=Date.now(),stages=['Reading your intent and boundaries','Reframing the main research question','Building analytical branches','Adding counterevidence and validation paths','Checking hierarchy and evidence targets'];let stage=0;$('#architectStatus').textContent=stages[0];$('#architectStatusDetail').textContent='AI question design usually takes 30–60 seconds · 0s elapsed';architectProgressTimer=setInterval(()=>{const elapsed=Math.floor((Date.now()-started)/1000);stage=Math.min(stages.length-1,Math.floor(elapsed/9));$('#architectStatus').textContent=stages[stage];$('#architectStatusDetail').textContent=`Working · ${elapsed}s elapsed · your current tree is unchanged`},1000);const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),90000);try{await ensureProject();architectureDraft=await api(`/projects/${projectId}/question-architect`,{method:'POST',signal:controller.signal,body:JSON.stringify({brain_dump,max_depth:Number($('#architectDepth').value),max_questions:Number($('#architectCount').value)})});renderArchitectureDraft()}catch(error){$('#architectEmpty').hidden=false;$('#architectStatus').textContent=error.name==='AbortError'?'Question design timed out':'Question Architect could not finish';$('#architectStatusDetail').textContent=error.name==='AbortError'?'Try again with a shorter subject or fewer questions.':error.message;missionMessage.textContent=`Question Architect failed: ${error.message}`}finally{clearTimeout(timeout);if(architectProgressTimer){clearInterval(architectProgressTimer);architectProgressTimer=null}$('#architectEmpty').classList.remove('working');$('#architectLoader').hidden=true;button.disabled=false;button.textContent='Generate question tree'}};
async function applyArchitecture(mode){if(!architectureDraft)return;const button=mode==='replace'?$('#replaceArchitecture'):$('#mergeArchitecture');button.disabled=true;try{await api(`/projects/${projectId}/question-architect/apply`,{method:'POST',body:JSON.stringify({architecture_id:architectureDraft.id,mode})});architectDlg.close();selectedQuestion=null;await loadTree();missionMessage.textContent=`AI question tree ${mode==='replace'?'replaced':'merged'} successfully.`}catch(error){missionMessage.textContent=`Could not apply AI tree: ${error.message}`}finally{button.disabled=false}}
$('#replaceArchitecture').onclick=()=>applyArchitecture('replace');$('#mergeArchitecture').onclick=()=>applyArchitecture('merge');
function resetInvestigationState(){if(missionTimer){clearInterval(missionTimer);missionTimer=null}if(gapPollTimer){clearTimeout(gapPollTimer);gapPollTimer=null}activeMission=null;coreTelemetry={signature:'',lastChange:Date.now(),data:null};findings.splice(0);library=[];bibliography=[];deepAnalysis=null;researchGaps=[];analysisRevisions=[];rootNode=null;questions=[];selectedQuestion=null;toggle.disabled=false;toggle.textContent='Start research';runStatus.textContent='Agents paused';renderCoreMonitor();render()}
async function loadProjectChoices(){try{const data=await api('/projects');$('#projectList').innerHTML=(data.projects||[]).map(p=>`<button class="project-choice ${p.id===projectId?'active':''}" data-project-id="${p.id}"><b>${escapeHtml(p.title)}</b><span>${escapeHtml(p.root_question||'No root question')}</span><small>${p.questions} questions · ${p.findings} findings</small></button>`).join('')||'<p class="sub">No saved investigations.</p>'}catch(error){$('#projectList').innerHTML=`<p class="sub">${escapeHtml(error.message)}</p>`}}
async function openInvestigationDialog(){await loadProjectChoices();$('#newProjectTitle').value='';$('#newProjectSubject').value='';investigationDlg.showModal()}
$('#newInvestigation').onclick=openInvestigationDialog;$('#openInvestigation').onclick=openInvestigationDialog;$('#cancelInvestigation').onclick=()=>investigationDlg.close();
async function switchProject(nextId){if(nextId===projectId){investigationDlg.close();return}projectId=nextId;localStorage.setItem('behiveProjectId',projectId);resetInvestigationState();investigationDlg.close();await loadTree();await resumeActiveResearch();missionMessage.textContent='Investigation switched.'}
$('#projectList').onclick=event=>{const choice=event.target.closest('[data-project-id]');if(choice)switchProject(choice.dataset.projectId)};
async function createNewInvestigation(useArchitect){const subject=$('#newProjectSubject').value.trim();if(subject.length<8){missionMessage.textContent='Enter a main subject or research question of at least 8 characters.';return}const title=$('#newProjectTitle').value.trim()||subject.replace(/\s+/g,' ').slice(0,90);const button=useArchitect?$('#createAndShape'):$('#createInvestigation');button.disabled=true;try{const created=await api('/projects',{method:'POST',body:JSON.stringify({title,root_question:subject.slice(0,2000),cadence_minutes:1440})});projectId=created.id;localStorage.setItem('behiveProjectId',projectId);localStorage.setItem(`behiveProjectInitialized:${projectId}`,'1');localStorage.removeItem(`behiveMission:${projectId}`);resetInvestigationState();investigationDlg.close();await loadTree();missionMessage.textContent='New investigation created. Refine the tree or start research.';if(useArchitect){$('#openArchitect').click();$('#architectDump').value=subject}}catch(error){missionMessage.textContent=`Could not create investigation: ${error.message}`}finally{button.disabled=false}}
$('#createInvestigation').onclick=()=>createNewInvestigation(false);$('#createAndShape').onclick=()=>createNewInvestigation(true);
function openAdd(){dialogMode='add';$('#questionDialogTitle').textContent=selectedQuestion?'Add child question':'Add research question';$('#questionText').value='';$('#questionPriority').value='0.5';$('#questionStatus').value='open';$('#questionParent').textContent=selectedQuestion?`Parent: ${selectedQuestion.title}`:'New top-level branch';$('#archiveQuestion').hidden=true;dlg.showModal()}
function openEdit(){if(!selectedQuestion)return;dialogMode='edit';$('#questionDialogTitle').textContent=selectedQuestion.isRoot?'Edit root research question':'Edit research question';$('#questionText').value=selectedQuestion.title;$('#questionPriority').value=selectedQuestion.priority;$('#questionStatus').value=selectedQuestion.status;$('#questionParent').textContent=selectedQuestion.isRoot?'Root of this investigation':`Depth ${selectedQuestion.depth}`;$('#archiveQuestion').hidden=Boolean(selectedQuestion.isRoot);dlg.showModal()}
$('#addQuestion').onclick=openAdd;$('#editQuestion').onclick=openEdit;
$('#rootTreeCard').onclick=()=>selectRoot();$('#rootTreeCard').ondblclick=async()=>{await selectRoot();if(selectedQuestion?.isRoot)openEdit()};
$('#rootTreeTitle').onclick=event=>event.stopPropagation();
$('#rootTreeTitle').ondblclick=event=>event.stopPropagation();
$('#rootTreeTitle').onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();event.currentTarget.blur()}};
$('#rootTreeTitle').onblur=async event=>{const question=event.currentTarget.textContent.trim();if(question.length<8){$('#missionMessage').textContent='Root question must be at least 8 characters.';if(rootNode)event.currentTarget.textContent=rootNode.label;return}try{if(!rootNode)await ensureProject();await api(`/projects/${projectId}/questions/${rootNode.id}`,{method:'PATCH',body:JSON.stringify({question})});rootNode.label=question;$('#rootQuestion').textContent=question;$('#missionMessage').textContent='Root question saved.'}catch(error){$('#missionMessage').textContent=`Could not save root question: ${error.message}`}};
dlg.addEventListener('close',async()=>{
 if(!['save','archive'].includes(dlg.returnValue))return;
 try{
  if(dlg.returnValue==='archive'){await api(`/projects/${projectId}/questions/${selectedQuestion.id}`,{method:'PATCH',body:JSON.stringify({status:'archived'})});selectedQuestion=null}
  else{const text=$('#questionText').value.trim();if(text.length<8)throw new Error('Question must be at least 8 characters');const payload={question:text,priority:Number($('#questionPriority').value),status:$('#questionStatus').value};if(dialogMode==='add'){payload.parent_id=selectedQuestion?.id||rootNode?.id;await api(`/projects/${projectId}/questions`,{method:'POST',body:JSON.stringify(payload)})}else await api(`/projects/${projectId}/questions/${selectedQuestion.id}`,{method:'PATCH',body:JSON.stringify(payload)})}
  await loadTree();$('#missionMessage').textContent='Question tree saved.';
 }catch(error){$('#missionMessage').textContent=`Could not save question: ${error.message}`}
});
$('#rootQuestion').addEventListener('blur',async()=>{if(!rootNode)return;const question=$('#rootQuestion').textContent.trim();if(question.length<8)return;try{await api(`/projects/${projectId}/questions/${rootNode.id}`,{method:'PATCH',body:JSON.stringify({question})});rootNode.label=question;$('#missionMessage').textContent='Root question saved.'}catch(error){$('#missionMessage').textContent=error.message}});
document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-panel]').forEach(x=>x.classList.remove('active'));b.classList.add('active');let graph=b.dataset.panel==='graph';$('#workspace').classList.toggle('hidden',graph);$('#graphView').classList.toggle('hidden',!graph)});
const toggle=$('#toggleRun'),runStatus=$('#runStatus'),missionMessage=$('#missionMessage');let activeMission=null,missionTimer=null;
const coreDefs=[['Plan','planning','Build research plan'],['Scout','scout','Discover sources'],['Harvest','harvest','Retrieve source content'],['Extract','process','Extract claims'],['Verify','falsify','Challenge evidence'],['Analyze','analyze','Compare mechanisms and scenarios'],['Synthesize','synth','Build conclusions'],['Connect','graph','Link knowledge graph']];
let coreTelemetry={signature:'',lastChange:Date.now(),data:null};
function effectiveCore(data){const names=coreDefs.map(c=>c[1]);const values=[data?.phase,data?.status].map(v=>(v||'').toLowerCase());let index=-1;values.forEach(v=>names.forEach((name,i)=>{if(v.includes(name))index=Math.max(index,i)}));if(values.includes('done')||values.includes('insufficient'))return names.length;return index<0?0:index}
function renderCoreMonitor(data=null){
 const count=data?.claims_so_far??data?.claims_count??0,status=(data?.status||'idle').toLowerCase(),activeIndex=effectiveCore(data),terminal=['done','insufficient','error','cancelled','interrupted'].includes(status),serverFailed=data?.watchdog?.state==='fail',stalled=!terminal&&activeMission&&(serverFailed||Date.now()-coreTelemetry.lastChange>180000);
 let summaryState='waiting',summary='No active mission',heartbeat='Waiting to start';
 if(activeMission){summaryState=['error','cancelled','interrupted'].includes(status)||serverFailed?'failed':status==='insufficient'?'no-results':status==='done'?(count?'complete':'no-results'):stalled?'stalled':'working';summary=['error','cancelled','interrupted'].includes(status)?`Research ${status}`:serverFailed?'Mission integrity failure':status==='insufficient'?'Complete · insufficient evidence':status==='done'?(count?`Complete · ${count} findings`:'Complete · no results'):stalled?'No progress detected':`${coreDefs[Math.min(activeIndex,coreDefs.length-1)][0]} core churning`;heartbeat=status==='insufficient'?'The retrieved material could not support defensible claims':serverFailed?'One or more watchdog tests failed':stalled?'No phase or finding change for 3+ minutes':`Last progress ${Math.max(0,Math.floor((Date.now()-coreTelemetry.lastChange)/1000))}s ago`}
 $('#coreSummaryDot').className=`core-state-dot ${summaryState}`;$('#coreSummary').textContent=summary;$('#coreHeartbeat').textContent=heartbeat;
 $('#coreGrid').innerHTML=coreDefs.map((core,i)=>{let state='waiting',label='Waiting';if(activeMission){if((status==='error'||serverFailed)&&i===activeIndex){state='failed';label='Failed'}else if(status==='done'||status==='insufficient'){state=count?'complete':(i>=3?'no-results':'complete');label=count?'Complete':(i>=3?'Insufficient':'Complete')}else if(i<activeIndex){state='complete';label='Complete'}else if(i===activeIndex){state=stalled?'stalled':'working';label=stalled?'No progress':'Churning'}}return `<div class="core-unit ${state}"><div class="core-unit-top"><b>${core[0]}</b><span class="core-unit-state">${label}</span></div><div class="activity-track"><i class="activity-bar"></i></div><small>${core[2]}</small></div>`}).join('');
 const checks=data?.watchdog?.checks||[{label:'Worker heartbeat',state:'unknown',detail:'No mission telemetry'},{label:'Phase consistency',state:'unknown',detail:'No mission telemetry'},{label:'Source-to-finding flow',state:'unknown',detail:'No mission telemetry'},{label:'Result production',state:'unknown',detail:'No mission telemetry'},{label:'Full mission completion',state:'unknown',detail:'No mission telemetry'}];
 $('#watchdogTests').innerHTML=checks.map(test=>`<div class="watchdog-test ${escapeHtml(test.state)}"><i></i><b>${escapeHtml(test.label)}</b><small>${escapeHtml(test.detail)}</small></div>`).join('');
 const failedCheck=checks.find(test=>test.state==='fail'),diagnostics=data?.diagnostics||{},failureStage=diagnostics.failure_stage||data?.phase||'last durable',attempt=Number(diagnostics.recovery_attempt||0),checkpoint=`${data?.sources_so_far||0} sources · ${data?.documents_so_far||0} documents · ${data?.claims_so_far||0} findings`;$('#recoveryControl').hidden=!(activeMission&&failedCheck);if(failedCheck)$('#recoveryReason').textContent=diagnostics.error_message?`${failureStage} failed: ${diagnostics.error_message}. Checkpoint preserved (${checkpoint}). ${attempt?`Previous recovery attempts: ${attempt}.`:''}`:`Recover ${failureStage} from preserved checkpoint: ${checkpoint}`;
}
$('#recoverMission').onclick=async()=>{if(!activeMission)return;const button=$('#recoverMission');button.disabled=true;button.textContent='Starting recovery…';try{const result=await api(`/research/${activeMission}/recover`,{method:'POST'});localStorage.setItem('behiveActiveMission',activeMission);coreTelemetry={signature:'',lastChange:Date.now(),data:null};$('#recoveryReason').textContent=`Attempt ${result.attempt||1}: ${result.message||`resuming from ${result.recovery_stage}`}`;missionMessage.textContent='Recovery started with prior sources and documents preserved.';await pollMission();if(!missionTimer)missionTimer=setInterval(pollMission,3000)}catch(error){missionMessage.textContent=`Recovery failed to start: ${error.message}`}finally{button.disabled=false;button.textContent='Recover failed stage'}};
async function pollMission(){if(!activeMission){renderCoreMonitor();return}try{const data=await api(`/research/${activeMission}/status`);const count=data.claims_so_far??data.claims_count??data.total_claims??0,signature=`${data.status}|${data.phase}|${count}`;if(signature!==coreTelemetry.signature){coreTelemetry.signature=signature;coreTelemetry.lastChange=Date.now()}coreTelemetry.data={...data,claims_so_far:count};renderCoreMonitor(coreTelemetry.data);runStatus.textContent=`${data.phase||data.status} · ${count} findings`;missionMessage.textContent=`Mission ${activeMission} · ${data.status} · ${data.phase||'starting'}`;if(['done','insufficient','error','cancelled','interrupted'].includes(data.status)){clearInterval(missionTimer);missionTimer=null;localStorage.removeItem('behiveActiveMission');toggle.disabled=false;toggle.textContent='Start another';if(['done','insufficient'].includes(data.status))await loadMissionResults()}}catch(error){runStatus.textContent='Status unavailable';missionMessage.textContent=error.message;$('#coreSummaryDot').className='core-state-dot failed';$('#coreSummary').textContent='Monitor offline';$('#coreHeartbeat').textContent=error.message}}
async function loadMissionResults(){try{const data=await api(`/research/${activeMission}`);const claims=data.claims||[];findings.splice(0,findings.length,...claims.slice(0,20).map(c=>({time:'NEW FINDING',score:Math.round((c.confidence||c.quality_score||0)*100),text:c.text||c.claim,source:c.source_url||'Source pending'})));render();missionMessage.textContent=`Complete · ${claims.length} sourced findings available`}catch(error){missionMessage.textContent=`Research complete; results unavailable: ${error.message}`}}
async function loadEvidenceCollections(){if(!activeMission)return;try{const data=await api(`/research/${activeMission}/evidence`);library=data.library||[];bibliography=data.bibliography||[];$('#navLibraryCount').textContent=library.length}catch(error){missionMessage.textContent=`Evidence library unavailable: ${error.message}`}}
async function loadDeepAnalysis(){if(!activeMission)return;try{deepAnalysis=(await api(`/research/${activeMission}/analysis`)).analysis}catch(error){deepAnalysis=null}}
async function loadGapControls(){if(!activeMission)return;try{const [g,r]=await Promise.all([api(`/research/${activeMission}/gaps`),api(`/research/${activeMission}/analysis/revisions`)]);researchGaps=g.gaps||[];analysisRevisions=r.revisions||[]}catch(error){researchGaps=[];analysisRevisions=[]}}
function gapCards(){return researchGaps.map(g=>{const active=['queued','scouting','harvesting','extracting','evaluating'].includes(g.status),pct=Math.min(100,Math.round((g.full_text_sources/g.target_sources)*75+(g.primary_sources/g.target_primary)*25));return `<article class="gap-card ${escapeHtml(g.status)}" data-gap-id="${g.id}"><div class="gap-top"><span>P${g.priority} · ${escapeHtml(g.status.toUpperCase())}</span><b>${g.full_text_sources}/${g.target_sources} full text · ${g.primary_sources}/${g.target_primary} primary</b></div><h4>${escapeHtml(g.question)}</h4><div class="evidence-progress"><i style="width:${pct}%"></i></div><p>${escapeHtml(g.message)}</p><div class="gap-actions">${active?'<button data-gap-action="pause">Pause</button>':'<button class="deepen" data-gap-action="deepen">Deepen research</button>'}<button data-gap-action="edit">Edit search</button><button data-gap-action="dismiss">Dismiss</button></div></article>`}).join('')||'<div class="empty-state">No open Analyst research gaps.</div>'}
function revisionCards(){return analysisRevisions.map(r=>`<article class="revision"><b>${escapeHtml(r.reason)}</b><span>${escapeHtml(r.created_at)} · claims ${r.previous_claims} → ${r.new_claims} · depth ${escapeHtml(r.previous_depth||'none')} → ${escapeHtml(r.new_depth||'unknown')}</span></article>`).join('')||'<p class="sub">No evidence-driven analysis revisions yet.</p>'}
function analysisCards(){if(!deepAnalysis)return '<div class="analysis-empty">Deep analysis has not been generated for this mission.</div>';const a=deepAnalysis,rankings=(a.rankings||[]).map((r,i)=>`<tr><td><b>${i+1}. ${escapeHtml(r.subject)}</b></td><td>${escapeHtml(r.direction||'—')}</td><td>${'●'.repeat(Math.max(0,Math.min(5,Number(r.magnitude)||0)))}${'○'.repeat(5-Math.max(0,Math.min(5,Number(r.magnitude)||0)))}</td><td>${escapeHtml(r.horizon||'—')}</td><td>${Math.round((Number(r.confidence)||0)*100)}%</td><td>${escapeHtml(r.mechanism||'')}</td></tr>`).join('');const deductions=(a.deductions||[]).map(d=>`<article class="analysis-item hypothesis"><span>HYPOTHESIS · ${Math.round((Number(d.confidence)||0)*100)}%</span><h4>${escapeHtml(d.deduction)}</h4><p>${escapeHtml(d.reasoning||'')}</p></article>`).join('');const scenarios=(a.scenarios||[]).map(s=>`<article class="analysis-item"><span>SCENARIO · ${Math.round((Number(s.confidence)||0)*100)}%</span><h4>${escapeHtml(s.name)}</h4><p><b>Trigger:</b> ${escapeHtml(s.trigger||'')}</p><p>${escapeHtml(Array.isArray(s.expected_effects)?s.expected_effects.join('; '):s.expected_effects||'')}</p></article>`).join('');return `<section class="analysis-hero ${escapeHtml(a.depth_status||'insufficient')}"><div><span>ANALYST CORE · ${(a.depth_status||'insufficient').toUpperCase()} EVIDENCE</span><h3>Deeper analysis</h3><p>${escapeHtml(a.executive_assessment||'')}</p></div><div class="depth-badge">${escapeHtml(a.depth_status||'insufficient')}</div></section><h3 class="analysis-heading">Comparative ranking</h3><div class="analysis-table-wrap"><table class="analysis-table"><thead><tr><th>Product group</th><th>Effect</th><th>Magnitude</th><th>Horizon</th><th>Confidence</th><th>Causal mechanism</th></tr></thead><tbody>${rankings||'<tr><td colspan="6">Insufficient evidence to rank.</td></tr>'}</tbody></table></div><div class="analysis-columns"><div><h3 class="analysis-heading">Scenario analysis</h3>${scenarios||'<p class="sub">No scenarios generated.</p>'}</div><div><h3 class="analysis-heading">Novel deductions</h3>${deductions||'<p class="sub">No defensible deductions yet.</p>'}</div></div><h3 class="analysis-heading">Targeted evidence acquisition</h3><div class="evidence-gate">Analysis-ready requires <b>3 independent full-text sources</b>, including <b>1 primary source</b>. Search snippets remain discovery records only.</div><div class="gap-grid">${gapCards()}</div><h3 class="analysis-heading">Analysis revision history</h3><div class="revision-list">${revisionCards()}</div><h3 class="analysis-heading">Limitations</h3><ul class="limitation-list">${(a.limitations||[]).map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul>`}
function findingCards(){return analysisCards()+`<h3 class="analysis-heading sourced-heading">Sourced findings</h3>`+(findings.map((f,i)=>`<article class="result-card"><div class="result-kicker"><span>Finding ${i+1}</span><b>${f.score}% confidence</b></div><h3>${escapeHtml(f.text)}</h3>${f.source?.startsWith('http')?`<a href="${escapeHtml(f.source)}" target="_blank" rel="noopener">Open supporting source ↗</a>`:'<span class="sub">Source pending</span>'}</article>`).join('')||'<div class="empty-state">No findings are available for this mission yet.</div>')}
function libraryCards(){return library.map((item,i)=>{const trust=[item.evidence_tier?`Tier ${item.evidence_tier}`:'Unranked',item.verification_status==='registry_verified'?'Registry verified':'Unverified',item.is_primary?'Primary record':'',item.is_open_access?'Open access':''].filter(Boolean).join(' · ');return `<article class="source-card"><div class="source-index">${String(i+1).padStart(2,'0')}</div><div><div class="result-kicker"><span>${escapeHtml(item.domain||'Source')}</span><b>${escapeHtml(trust)}</b></div><h3>${escapeHtml(item.title)}</h3><p>${item.word_count} words · ${escapeHtml(item.harvest_method)} · quality ${Math.round(item.quality_score*100)}%${item.persistent_id?` · ${escapeHtml(item.persistent_id)}`:''}</p><a href="${escapeHtml(item.url)}" target="_blank" rel="noopener">Open source ↗</a></div></article>`}).join('')||'<div class="empty-state">No harvested documents are available yet.</div>'}
function bibliographyRows(){return bibliography.map(item=>`<li><span class="bib-number">${item.number}.</span><div>${item.author?`${escapeHtml(item.author)}. `:''}<cite>${escapeHtml(item.title)}</cite>. ${item.published_date?`${escapeHtml(item.published_date)}. `:''}<a href="${escapeHtml(item.url)}" target="_blank" rel="noopener">${escapeHtml(item.domain||item.url)}</a>${item.persistent_id?` <small>${escapeHtml(item.persistent_id)}</small>`:''}${item.verification_status==='registry_verified'?` <b>Registry verified · Tier ${item.evidence_tier||'—'}${item.is_primary?' · Primary record':''}.</b>`:''}${item.supports_findings?` <b>Supports ${item.supports_findings} finding${item.supports_findings===1?'':'s'}.</b>`:''}</div></li>`).join('')||'<div class="empty-state">No bibliography entries are available yet.</div>'}
async function showView(view){if(view!=='graph')$('.shell').classList.remove('discovery-mode');if(gapPollTimer){clearTimeout(gapPollTimer);gapPollTimer=null}document.querySelectorAll('nav button[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===view));const graph=view==='graph',overview=['overview','questions'].includes(view);$('#workspace').classList.toggle('hidden',!overview);$('#graphView').classList.toggle('hidden',!graph);$('#collectionView').classList.toggle('hidden',overview||graph);if(['findings','library','bibliography'].includes(view)){await loadEvidenceCollections();if(view==='findings'){await Promise.all([loadDeepAnalysis(),loadGapControls()])}const config={findings:['FINDINGS + ANALYSIS','Research findings',`${findings.length} evidence-linked findings with analytical interpretation`,findingCards()],library:['SOURCE LIBRARY','Research library',`${library.length} recovered or harvested documents`,libraryCards()],bibliography:['BIBLIOGRAPHY','Sources and citations',`${bibliography.length} unique sources`,`<ol class="bibliography-list">${bibliographyRows()}</ol>`]}[view];$('#collectionEyebrow').textContent=config[0];$('#collectionTitle').textContent=config[1];$('#collectionSummary').textContent=config[2];$('#collectionBody').innerHTML=config[3];if(view==='findings'&&researchGaps.some(g=>['queued','scouting','harvesting','extracting','evaluating'].includes(g.status)))gapPollTimer=setTimeout(()=>showView('findings'),5000)}}
document.querySelectorAll('nav button[data-view]').forEach(button=>button.onclick=()=>showView(button.dataset.view));
$('#collectionBody').onclick=async event=>{const button=event.target.closest('[data-gap-action]');if(!button||!activeMission)return;const card=button.closest('[data-gap-id]'),gapId=card?.dataset.gapId,action=button.dataset.gapAction;if(!gapId)return;button.disabled=true;try{if(action==='edit'){const current=researchGaps.find(g=>String(g.id)===String(gapId));const question=window.prompt('Edit targeted research question',current?.question||'');if(!question){button.disabled=false;return}await api(`/research/${activeMission}/gaps/${gapId}`,{method:'PATCH',body:JSON.stringify({question})})}else await api(`/research/${activeMission}/gaps/${gapId}/${action}`,{method:'POST'});await showView('findings')}catch(error){missionMessage.textContent=`Gap action failed: ${error.message}`;button.disabled=false}};
toggle.onclick=async()=>{const question=$('#rootQuestion').textContent.trim();if(question.length<8){missionMessage.textContent='Enter a research question of at least 8 characters.';return}toggle.disabled=true;toggle.textContent='Starting…';runStatus.textContent='Starting research';try{await ensureProject();const data=await api('/research',{method:'POST',body:JSON.stringify({query:question,depth:3,scale:30})});activeMission=data.job_id||data.mission_id;localStorage.setItem('behiveActiveMission',activeMission);localStorage.setItem(`behiveMission:${projectId}`,activeMission);localStorage.setItem(`behiveProjectInitialized:${projectId}`,'1');coreTelemetry={signature:'',lastChange:Date.now(),data:null};toggle.textContent='Research running';await pollMission();missionTimer=setInterval(pollMission,3000)}catch(error){toggle.disabled=false;toggle.textContent='Start research';runStatus.textContent='Could not start';missionMessage.textContent=error.message}};
['budget','maxAgents'].forEach(id=>$('#'+id).oninput=e=>$('#'+id.replace('maxAgents','agents')+'Out').textContent=e.target.value);$('#autonomy').onchange=e=>$('#autonomyBadge').textContent=e.target.value.toUpperCase();$('#savePolicy').onclick=async e=>{try{await ensureProject();await api(`/projects/${projectId}/policy`,{method:'PUT',body:JSON.stringify({autonomy:$('#autonomy').value,status:'paused',daily_budget:Number($('#budget').value),max_agents:Number($('#maxAgents').value),max_depth:5,min_confidence:.7,primary_sources_required:true,approval_new_branches:true,freshness_days:30})});e.target.textContent='Saved ✓'}catch(error){missionMessage.textContent=error.message}setTimeout(()=>e.target.textContent='Save policy',1300)};
async function resumeActiveResearch(){try{const initialized=localStorage.getItem(`behiveProjectInitialized:${projectId}`)==='1',saved=localStorage.getItem(`behiveMission:${projectId}`);const data=await api('/missions?limit=40');const missions=(data.missions||[]).filter(m=>!String(m.id||'').startsWith('gap_'));let mission=saved?missions.find(m=>m.id===saved):null;if(!mission&&!initialized&&rootNode)mission=missions.find(m=>String(m.topic||'').trim().toLowerCase()===String(rootNode.label||'').trim().toLowerCase())||missions[0];if(!mission){activeMission=null;toggle.disabled=false;toggle.textContent='Start research';renderCoreMonitor();return}activeMission=mission.id;localStorage.setItem(`behiveMission:${projectId}`,activeMission);localStorage.setItem(`behiveProjectInitialized:${projectId}`,'1');toggle.disabled=true;toggle.textContent='Research running';await pollMission();if(!['done','insufficient','error','cancelled','interrupted'].includes(mission.status)&&!missionTimer)missionTimer=setInterval(pollMission,3000)}catch(error){renderCoreMonitor()}}
async function bootstrap(){render();renderCoreMonitor();await ensureProject();await resumeActiveResearch()}
bootstrap();
document.querySelectorAll('button[data-view="graph"]').forEach(button=>button.onclick=showDiscoveryLab);
document.querySelectorAll('button[data-panel="graph"]').forEach(button=>button.onclick=showDiscoveryLab);
document.querySelectorAll('button[data-view]:not([data-view="graph"]),button[data-panel]:not([data-panel="graph"])').forEach(button=>button.addEventListener('click',()=>{$('#discoveryView').classList.add('hidden');$('.shell').classList.remove('discovery-mode')}));
document.querySelectorAll('[data-frontier-panel]').forEach(button=>button.onclick=()=>{frontierPanel=button.dataset.frontierPanel;document.querySelectorAll('[data-frontier-panel]').forEach(b=>b.classList.toggle('active',b===button));renderLabRail()});
